DROP TABLE IF EXISTS eventos;
CREATE TABLE eventos
(
id_Evento INT GENERATED BY default as IDENTITY not null,
description VARCHAR(100),
capacity INT,
start_Date TIMESTAMP,
end_Date TIMESTAMP,
price DOUBLE
);

INSERT INTO eventos (description, capacity, start_Date, end_Date, price)
VALUES ('Concierto de Rock', 500, '2023-06-10 19:00:00', '2023-06-10 23:00:00', 50.99);
INSERT INTO eventos (description, capacity, start_Date, end_Date, price)
VALUES ('Obra de Teatro: Hamlet', 200, '2023-07-05 20:00:00', '2023-07-05 22:30:00', 35.50);
